In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
df1 = pd.read_csv("D:\\Documents\\Hero Vired\\Python for Data Analysis\\Assignment 4\\superstore.csv")

In [13]:
df1.shape

(51290, 27)

In [14]:
df1.head(5)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,00:00.0,CA-2011-130813,...,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,00:00.0,CA-2011-148614,...,19,Consumer,00:00.0,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,21,Consumer,00:00.0,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,111,Consumer,00:00.0,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,00:00.0,CA-2011-146969,...,6,Consumer,00:00.0,Standard Class,1.32,California,Paper,2011,North America,40

In [31]:
print("n\Columns: ")
df1.columns.to_list()

n\Columns:

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\vnaya\AppData\Local\Temp\ipykernel_8884\4205767829.py:1: SyntaxWarning: invalid escape sequence '\C'
  print("n\Columns: ")

['Category',
 'City',
 'Country',
 'Customer.ID',
 'Customer.Name',
 'Discount',
 'Market',
 '记录数',
 'Order.Date',
 'Order.ID',
 'Order.Priority',
 'Product.ID',
 'Product.Name',
 'Profit',
 'Quantity',
 'Region',
 'Row.ID',
 'Sales',
 'Segment',
 'Ship.Date',
 'Ship.Mode',
 'Shipping.Cost',
 'State',
 'Sub.Category',
 'Year',
 'Market2',
 'weeknum']

In [32]:
df1.dtypes

Category              str
City                  str
Country               str
Customer.ID           str
Customer.Name         str
Discount          float64
Market                str
记录数                 int64
Order.Date            str
Order.ID              str
Order.Priority        str
Product.ID            str
Product.Name          str
Profit            float64
Quantity            int64
Region                str
Row.ID              int64
Sales               int64
Segment               str
Ship.Date             str
Ship.Mode             str
Shipping.Cost     float64
State                 str
Sub.Category          str
Year                int64
Market2               str
weeknum             int64
dtype: object

In [ ]:
#Convert Data Types
df1[['Customer.ID', 'Product.ID', 'Order.ID']]

In [17]:
missing_values = df1.isnull().sum()
duplicate_values = df1.duplicated().sum()

print("Missing Values: ", missing_values)
print("Duplicate Values: ", duplicate_values)

Missing Values:  Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     5
State             3
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64
Duplicate Values:  0

In [18]:
range_check = pd.DataFrame({
    "Min": df1[['Discount']].min(),
    "Max": df1[['Discount']].max()
})

range_check

          Min   Max
Discount  0.0  0.85

In [44]:
identifier_cols = ['Customer.ID']
categorical_cols = ['Segment', 'Sub.Category', 'Market', 'Market2', 'Region', 'Category', 'Ship.Mode', 'Order.Priority']
numeric_cols = ['Sales', 'Quantity', 'Discount', 'Profit']
target_col = 'Profit'

print("Identifier Columns: ", identifier_cols)
print("Categorical Columns: ", categorical_cols)
print("Numeric Columns: ", numeric_cols)
print("Target Column: ", target_col)

Identifier Columns:  ['Customer.ID']
Categorical Columns:  ['Segment', 'Sub.Category', 'Market', 'Market2', 'Region', 'Category', 'Ship.Mode', 'Order.Priority']
Numeric Columns:  ['Sales', 'Quantity', 'Discount', 'Profit']
Target Column:  Profit

In [34]:
#Descriptive Statistics
summary_stats = df1[numeric_cols].describe().T
display(summary_stats)

,count,mean,std,min,25%,50%,75%,max
Sales,51290.0,246.498440,487.567175,0.000,31.0,85.00,251.00,22638.000
Quantity,51290.0,3.476545,2.278766,1.000,2.0,3.00,5.00,14.000
Discount,51290.0,0.142908,0.212280,0.000,0.0,0.00,0.20,0.850
Profit,51290.0,28.610982,174.340972,-6599.978,0.0,9.24,36.81,8399.976

In [47]:
#Frequency Distribution for Categorical Variables
for col in categorical_cols:
    print(f"\n====={col}====")
    counts = df1[col].value_counts(dropna = False)
    percentages = round(df1[col].value_counts(normalize = True, dropna = False) *100, 2)

    summary = pd.DataFrame({
        "count": counts,
        "percentage": percentages
    })

    display(summary)

=====Segment====

             count  percentage
Segment
Consumer     26518       51.70
Corporate    15429       30.08
Home Office   9343       18.22

=====Sub.Category====

              count  percentage
Sub.Category
Binders        6152       11.99
Storage        5059        9.86
Art            4883        9.52
Paper          3538        6.90
Chairs         3434        6.70
Phones         3357        6.55
Furnishings    3170        6.18
Accessories    3075        6.00
Labels         2606        5.08
Envelopes      2435        4.75
Supplies       2425        4.73
Fasteners      2420        4.72
Bookcases      2411        4.70
Copiers        2223        4.33
Appliances     1755        3.42
Machines       1486        2.90
Tables          861        1.68

=====Market====

        count  percentage
Market
APAC    11002       21.45
LATAM   10294       20.07
EU      10000       19.50
US       9994       19.49
EMEA     5029        9.81
Africa   4587        8.94
Canada    384        0.75

=====Market2====

               count  percentage
Market2
APAC           11002       21.45
North America  10378       20.23
LATAM          10294       20.07
EU             10000       19.50
EMEA            5029        9.81
Africa          4587        8.94

=====Region====

                count  percentage
Region
Central         11117       21.67
South            6645       12.96
EMEA             5029        9.81
North            4785        9.33
Africa           4587        8.94
Oceania          3487        6.80
West             3203        6.24
Southeast Asia   3129        6.10
East             2848        5.55
North Asia       2338        4.56
Central Asia     2048        3.99
Caribbean        1690        3.29
Canada            384        0.75

=====Category====

                 count  percentage
Category
Office Supplies  31273       60.97
Technology       10141       19.77
Furniture         9876       19.26

=====Ship.Mode====

                count  percentage
Ship.Mode
Standard Class  30775       60.00
Second Class    10309       20.10
First Class      7505       14.63
Same Day         2701        5.27

=====Order.Priority====

                count  percentage
Order.Priority
Medium          29433       57.39
High            15501       30.22
Critical         3932        7.67
Low              2424        4.73

In [ ]:
#Target Variable Analysis